# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-15 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import shortener.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_auto_20161209_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tackkleurl',
            name='url',
            field=models.CharField(max_length=220, validators=[shortener.validators.validate_url, shortener.validators.validate_dot_com]),
        ),
    ]
